export class Columns {
    public static matterColumns: any = ['SHORTNAME', 'MATTER', 'CONTACTNAME', 'CONTACTFIRMNAME', 'MATTERCLASS', 'MATTERTYPE', 'CLIENT', 'REFERENCE', 'UNBILLED', 'INVOICED', 'RECEIVED', 'WRITTENOFF', 'OUTSTANDING', 'TOTALVALUE', 'UNPAID', 'ESTIMATE', 'RATEPERHOUR', 'RATEPERDAY', 'FEEAGREEMENTDATE', 'BILLINGMETHOD', 'GSTTYPE', 'CLIENTSTATUS', 'MATTERNO', 'ACTIVE'];
}
