export class Columns {
    public static matterColumns: any = ['SHORTNAME', 'MATTER', 'CONTACTNAME', 'CONTACTFIRMNAME', 'MATTERCLASS', 'MATTERTYPE', 'CLIENT', 'REFERENCE', 'UNBILLED', 'INVOICED', 'RECEIVED', 'WRITTENOFF', 'OUTSTANDING', 'TOTALVALUE', 'UNPAID', 'ESTIMATE', 'RATEPERHOUR', 'RATEPERDAY', 'FEEAGREEMENTDATE', 'BILLINGMETHOD', 'GSTTYPE', 'CLIENTSTATUS', 'MATTERNO', 'ACTIVE'];
    public static contactColumns: any = ['COMPANYCONTACTGUID', 'CONTACTTYPE', 'USERGUID', 'USEPARENTADDRESS', 'CONTACTNAME', 'SALUTATION', 'POSITION', 'NAMETITLE',
        'GIVENNAMES', 'MIDDLENAMES', 'FAMILYNAME', 'NAMELETTERS', 'KNOWNBYOTHERNAME', 'OTHERFAMILYNAME', 'OTHERGIVENNAMES', 'REASONFORCHANGE', 'MARITALSTATUS',
        'SPOUSE', 'NUMBEROFDEPENDANTS', 'OCCUPATION', 'GENDER', 'DATEOFBIRTH', 'BIRTHDAYREMINDER', 'TOWNOFBIRTH', 'COUNTRYOFBIRTH', 'CAUSEOFDEATH', 'ADDRESS1'
        , 'ADDRESS1', 'ADDRESS2', 'ADDRESS3', 'SUBURB', 'STATE', 'POSTCODE', 'COUNTRY', 'SAMEASSTREET', 'POSTALADDRESS1', 'POSTALADDRESS2', 'POSTALADDRESS3',
        'POSTALSUBURB', 'POSTALSTATE', 'POSTALPOSTCODE', 'POSTALCOUNTRY', 'DX', 'DXSUBURB', 'PHONE', 'PHONE2', 'FAX', 'FAX2', 'MOBILE', 'EMAIL', 'EMAIL2',
        'ELECTRONICSERVICEEMAIL', 'WEBADDRESS', 'SKYPEUSERNAME', 'MESSENGERUSERNAME', 'ACN', 'ABN', 'PRACTICINGCERTIFICATENO', 'TFN', 'LICENCENO', 'LICENCECOUNTRY',
        'LICENCESCANLOCATION', 'NATIONALIDENTITYNO', 'NATIONALIDENTITYCOUNTRY', 'NATIDENTSCANLOCATION', 'FAMILYCOURTLAWYERNO', 'ASSOCIATIONNO', 'GSTTYPE',
        'DEFAULTCURRENCYID', 'PHOTOGRAPH', 'NOTES', 'ACTIVE', 'SOPHISTICATEDCLIENT', 'CLIENTSOURCE', 'COMPANYNAME'];
}
